import type { ImportMap } from "payload";

// @ts-expect-error Generated by Payload CLI at runtime; no declaration file is emitted.
import { importMap as generatedImportMap } from "./importMap.js";

export const importMap: ImportMap = generatedImportMap;
