import type { SiteLocale } from "@/config/i18n";
import type { CmsProductInquiryField, CmsProductInquiryForm } from "@/lib/cms/types";

type InquiryUiCopy = {
  selectPlaceholder: string;
  filePlaceholderNote: string;
  errorSummaryTitle: string;
  submittingButton: string;
  successTitle: string;
  successMessage: string;
  submissionUnavailableTitle: string;
  submittingTitle: string;
  validationPassedTitle: string;
  submittingDescription: string;
  validationPassedDescription: string;
  requestSaveUnavailable: string;
  requestServiceUnavailable: string;
  honeypotLabel: string;
  requiredConsent: string;
  invalidEmail: string;
  invalidPhone: string;
  invalidNumber: string;
  invalidDate: string;
  successReferenceLabel: string;
  requiredField(label: string): string;
  chooseField(label: string): string;
};

const inquiryUiCopyByLocale: Record<SiteLocale, InquiryUiCopy> = {
  en: {
    selectPlaceholder: "Select an option",
    filePlaceholderNote: "Share files with the advisor after the first consultation.",
    errorSummaryTitle: "Review required fields",
    submittingButton: "Submitting...",
    successTitle: "Request captured",
    successMessage: "The request was saved and sent to the Montelar team.",
    submissionUnavailableTitle: "Submission unavailable",
    submittingTitle: "Submitting request",
    validationPassedTitle: "Validation passed locally",
    submittingDescription: "Saving the private request with a reference code.",
    validationPassedDescription:
      "The request is ready to be sent.",
    requestSaveUnavailable: "The request could not be saved right now.",
    requestServiceUnavailable: "The request service is temporarily unavailable.",
    honeypotLabel: "Company website",
    requiredConsent: "Confirm consent to continue.",
    invalidEmail: "Enter a valid email address.",
    invalidPhone: "Enter a valid phone number.",
    invalidNumber: "Enter a valid number.",
    invalidDate: "Enter a valid date.",
    successReferenceLabel: "Reference",
    requiredField: (label) => `Provide ${label}.`,
    chooseField: (label) => `Choose ${label}.`,
  },
  ru: {
    selectPlaceholder: "Выберите вариант",
    filePlaceholderNote: "Файлы можно будет передать консультанту после первой консультации.",
    errorSummaryTitle: "Проверьте обязательные поля",
    submittingButton: "Отправка...",
    successTitle: "Заявка принята",
    successMessage: "Заявка сохранена и передана на дальнейшую обработку.",
    submissionUnavailableTitle: "Отправка недоступна",
    submittingTitle: "Отправляем заявку",
    validationPassedTitle: "Проверка формы пройдена",
    submittingDescription: "Сохраняем заявку и служебный идентификатор.",
    validationPassedDescription:
      "Заявка готова к отправке.",
    requestSaveUnavailable: "Сейчас не удалось сохранить заявку.",
    requestServiceUnavailable: "Сервис приёма заявок сейчас недоступен.",
    honeypotLabel: "Сайт компании",
    requiredConsent: "Подтвердите согласие, чтобы продолжить.",
    invalidEmail: "Укажите корректный email.",
    invalidPhone: "Укажите корректный номер телефона.",
    invalidNumber: "Укажите корректное число.",
    invalidDate: "Укажите корректную дату.",
    successReferenceLabel: "Код",
    requiredField: (label) => `Укажите ${label}.`,
    chooseField: (label) => `Выберите ${label}.`,
  },
  es: {
    selectPlaceholder: "Selecciona una opción",
    filePlaceholderNote: "Los archivos se podrán compartir con el asesor tras la primera consulta.",
    errorSummaryTitle: "Revisa los campos obligatorios",
    submittingButton: "Enviando...",
    successTitle: "Solicitud registrada",
    successMessage: "La solicitud se guardó y se envió para seguimiento.",
    submissionUnavailableTitle: "Envío no disponible",
    submittingTitle: "Enviando solicitud",
    validationPassedTitle: "Validación local completada",
    submittingDescription: "Guardando la solicitud privada y su referencia.",
    validationPassedDescription:
      "La solicitud está lista para enviarse.",
    requestSaveUnavailable: "No se pudo guardar la solicitud en este momento.",
    requestServiceUnavailable: "El servicio de solicitudes no está disponible temporalmente.",
    honeypotLabel: "Sitio web de la empresa",
    requiredConsent: "Confirma el consentimiento para continuar.",
    invalidEmail: "Introduce un correo electrónico válido.",
    invalidPhone: "Introduce un número de teléfono válido.",
    invalidNumber: "Introduce un número válido.",
    invalidDate: "Introduce una fecha válida.",
    successReferenceLabel: "Referencia",
    requiredField: (label) => `Indica ${label}.`,
    chooseField: (label) => `Selecciona ${label}.`,
  },
  fr: {
    selectPlaceholder: "Sélectionnez une option",
    filePlaceholderNote: "Les fichiers pourront être partagés avec le conseiller après la première consultation.",
    errorSummaryTitle: "Vérifiez les champs obligatoires",
    submittingButton: "Envoi...",
    successTitle: "Demande enregistrée",
    successMessage: "La demande a été enregistrée et transmise pour suivi.",
    submissionUnavailableTitle: "Envoi indisponible",
    submittingTitle: "Envoi de la demande",
    validationPassedTitle: "Validation locale réussie",
    submittingDescription: "Enregistrement de la demande privée et de sa référence.",
    validationPassedDescription:
      "La demande est prête à être envoyée.",
    requestSaveUnavailable: "La demande ne peut pas être enregistrée pour le moment.",
    requestServiceUnavailable: "Le service de demandes est temporairement indisponible.",
    honeypotLabel: "Site web de l’entreprise",
    requiredConsent: "Confirmez le consentement pour continuer.",
    invalidEmail: "Saisissez une adresse e-mail valide.",
    invalidPhone: "Saisissez un numéro de téléphone valide.",
    invalidNumber: "Saisissez un nombre valide.",
    invalidDate: "Saisissez une date valide.",
    successReferenceLabel: "Référence",
    requiredField: (label) => `Renseignez ${label}.`,
    chooseField: (label) => `Choisissez ${label}.`,
  },
  zh: {
    selectPlaceholder: "请选择一项",
    filePlaceholderNote: "文件可在首次咨询后与顾问共享。",
    errorSummaryTitle: "请检查必填字段",
    submittingButton: "提交中...",
    successTitle: "请求已记录",
    successMessage: "请求已保存并转入后续跟进。",
    submissionUnavailableTitle: "当前无法提交",
    submittingTitle: "正在提交请求",
    validationPassedTitle: "本地校验已通过",
    submittingDescription: "正在保存私人咨询请求和参考编号。",
    validationPassedDescription: "咨询请求已准备好提交。",
    requestSaveUnavailable: "当前无法保存请求。",
    requestServiceUnavailable: "咨询服务暂时不可用。",
    honeypotLabel: "公司网站",
    requiredConsent: "请确认同意后继续。",
    invalidEmail: "请输入有效的邮箱地址。",
    invalidPhone: "请输入有效的电话号码。",
    invalidNumber: "请输入有效的数字。",
    invalidDate: "请输入有效的日期。",
    successReferenceLabel: "编号",
    requiredField: (label) => `请填写${label}。`,
    chooseField: (label) => `请选择${label}。`,
  },
  ja: {
    selectPlaceholder: "選択してください",
    filePlaceholderNote: "ファイルは初回相談後にアドバイザーへ共有できます。",
    errorSummaryTitle: "必須項目を確認してください",
    submittingButton: "送信中...",
    successTitle: "リクエストを受け付けました",
    successMessage: "リクエストは保存され、次の対応へ引き渡されました。",
    submissionUnavailableTitle: "現在送信できません",
    submittingTitle: "リクエストを送信しています",
    validationPassedTitle: "ローカル検証が完了しました",
    submittingDescription: "プライベート相談依頼と参照コードを保存しています。",
    validationPassedDescription:
      "相談依頼を送信できます。",
    requestSaveUnavailable: "現在このリクエストを保存できません。",
    requestServiceUnavailable: "相談サービスは一時的に利用できません。",
    honeypotLabel: "会社のウェブサイト",
    requiredConsent: "続行するには同意を確認してください。",
    invalidEmail: "有効なメールアドレスを入力してください。",
    invalidPhone: "有効な電話番号を入力してください。",
    invalidNumber: "有効な数値を入力してください。",
    invalidDate: "有効な日付を入力してください。",
    successReferenceLabel: "参照番号",
    requiredField: (label) => `${label}を入力してください。`,
    chooseField: (label) => `${label}を選択してください。`,
  },
  de: {
    selectPlaceholder: "Option auswählen",
    filePlaceholderNote: "Dateien können nach der ersten Beratung mit dem Advisor geteilt werden.",
    errorSummaryTitle: "Pflichtfelder prüfen",
    submittingButton: "Wird gesendet...",
    successTitle: "Anfrage erfasst",
    successMessage: "Die Anfrage wurde gespeichert und zur Nachverfolgung weitergeleitet.",
    submissionUnavailableTitle: "Senden nicht verfügbar",
    submittingTitle: "Anfrage wird gesendet",
    validationPassedTitle: "Lokale Prüfung bestanden",
    submittingDescription: "Private Anfrage und Referenzcode werden gespeichert.",
    validationPassedDescription:
      "Die Anfrage ist bereit zum Senden.",
    requestSaveUnavailable: "Die Anfrage konnte gerade nicht gespeichert werden.",
    requestServiceUnavailable: "Der Anfragedienst ist vorübergehend nicht verfügbar.",
    honeypotLabel: "Unternehmenswebsite",
    requiredConsent: "Bestätigen Sie die Einwilligung, um fortzufahren.",
    invalidEmail: "Geben Sie eine gültige E-Mail-Adresse ein.",
    invalidPhone: "Geben Sie eine gültige Telefonnummer ein.",
    invalidNumber: "Geben Sie eine gültige Zahl ein.",
    invalidDate: "Geben Sie ein gültiges Datum ein.",
    successReferenceLabel: "Referenz",
    requiredField: (label) => `Bitte ${label} angeben.`,
    chooseField: (label) => `Bitte ${label} auswählen.`,
  },
};

const sharedFieldLabelByKey: Partial<Record<string, Record<SiteLocale, string>>> = {
  fullName: {
    en: "Full name",
    ru: "Полное имя",
    es: "Nombre completo",
    fr: "Nom complet",
    zh: "姓名",
    ja: "氏名",
    de: "Vollständiger Name",
  },
  email: {
    en: "Email",
    ru: "Email",
    es: "Correo electrónico",
    fr: "E-mail",
    zh: "邮箱",
    ja: "メールアドレス",
    de: "E-Mail",
  },
  phone: {
    en: "Phone",
    ru: "Телефон",
    es: "Teléfono",
    fr: "Téléphone",
    zh: "电话",
    ja: "電話番号",
    de: "Telefon",
  },
  country: {
    en: "Country",
    ru: "Страна",
    es: "País",
    fr: "Pays",
    zh: "国家",
    ja: "国",
    de: "Land",
  },
  city: {
    en: "City",
    ru: "Город",
    es: "Ciudad",
    fr: "Ville",
    zh: "城市",
    ja: "都市",
    de: "Stadt",
  },
  preferredLanguage: {
    en: "Preferred language",
    ru: "Предпочтительный язык",
    es: "Idioma preferido",
    fr: "Langue préférée",
    zh: "偏好语言",
    ja: "希望言語",
    de: "Bevorzugte Sprache",
  },
  companyOrOffice: {
    en: "Company / family office",
    ru: "Компания / family office",
    es: "Empresa / family office",
    fr: "Société / family office",
    zh: "公司 / 家族办公室",
    ja: "会社 / ファミリーオフィス",
    de: "Unternehmen / Family Office",
  },
  companyOrStudio: {
    en: "Company / studio / family office",
    ru: "Компания / студия / family office",
    es: "Empresa / estudio / family office",
    fr: "Société / studio / family office",
    zh: "公司 / 工作室 / 家族办公室",
    ja: "会社 / スタジオ / ファミリーオフィス",
    de: "Unternehmen / Studio / Family Office",
  },
  companyOrBrand: {
    en: "Company / brand / family office",
    ru: "Компания / бренд / family office",
    es: "Empresa / marca / family office",
    fr: "Société / marque / family office",
    zh: "公司 / 品牌 / 家族办公室",
    ja: "会社 / ブランド / ファミリーオフィス",
    de: "Unternehmen / Marke / Family Office",
  },
  organization: {
    en: "Organization / institution / brand",
    ru: "Организация / институция / бренд",
    es: "Organización / institución / marca",
    fr: "Organisation / institution / marque",
    zh: "机构 / 场馆 / 品牌",
    ja: "組織 / 施設 / ブランド",
    de: "Organisation / Institution / Marke",
  },
  preferredContactMethod: {
    en: "Preferred contact method",
    ru: "Предпочтительный способ связи",
    es: "Forma de contacto preferida",
    fr: "Mode de contact préféré",
    zh: "首选联系方式",
    ja: "希望する連絡方法",
    de: "Bevorzugter Kontaktweg",
  },
  projectType: {
    en: "Project type",
    ru: "Тип проекта",
    es: "Tipo de proyecto",
    fr: "Type de projet",
    zh: "项目类型",
    ja: "プロジェクト種別",
    de: "Projekttyp",
  },
  residenceType: {
    en: "Residence type",
    ru: "Тип резиденции",
    es: "Tipo de residencia",
    fr: "Type de résidence",
    zh: "住宅类型",
    ja: "住居タイプ",
    de: "Residenztyp",
  },
  newBuildOrRetrofit: {
    en: "Project context",
    ru: "Тип работ",
    es: "Ruta del proyecto",
    fr: "Parcours du projet",
    zh: "项目路径",
    ja: "プロジェクト区分",
    de: "Projektpfad",
  },
  projectPath: {
    en: "Project context",
    ru: "Тип работ",
    es: "Ruta del proyecto",
    fr: "Parcours du projet",
    zh: "项目路径",
    ja: "プロジェクト区分",
    de: "Projektpfad",
  },
  projectStage: {
    en: "Current project stage",
    ru: "Текущая стадия проекта",
    es: "Fase actual del proyecto",
    fr: "Phase actuelle du projet",
    zh: "当前项目阶段",
    ja: "現在のプロジェクト段階",
    de: "Aktuelle Projektphase",
  },
  timeline: {
    en: "Project timeline",
    ru: "Сроки проекта",
    es: "Calendario del proyecto",
    fr: "Calendrier du projet",
    zh: "项目时间表",
    ja: "プロジェクト時期",
    de: "Projektzeitplan",
  },
  budgetBand: {
    en: "Budget band",
    ru: "Диапазон бюджета",
    es: "Rango de presupuesto",
    fr: "Fourchette budgétaire",
    zh: "预算范围",
    ja: "予算帯",
    de: "Budgetrahmen",
  },
  stakeholders: {
    en: "Stakeholders already involved",
    ru: "Уже подключенные участники",
    es: "Partes ya involucradas",
    fr: "Intervenants déjà impliqués",
    zh: "已参与的相关方",
    ja: "既に関与している関係者",
    de: "Bereits beteiligte Parteien",
  },
  roomType: {
    en: "Room type",
    ru: "Тип помещения",
    es: "Tipo de sala",
    fr: "Type de pièce",
    zh: "空间类型",
    ja: "部屋の種類",
    de: "Raumtyp",
  },
  roomDimensions: {
    en: "Approximate room dimensions",
    ru: "Ориентировочные размеры помещения",
    es: "Dimensiones aproximadas de la sala",
    fr: "Dimensions approximatives de la pièce",
    zh: "空间大致尺寸",
    ja: "部屋のおおよその寸法",
    de: "Ungefähre Raummaße",
  },
  roomSize: {
    en: "Approximate room size",
    ru: "Ориентировочный размер помещения",
    es: "Tamaño aproximado de la sala",
    fr: "Taille approximative de la pièce",
    zh: "空间大致面积",
    ja: "部屋のおおよその広さ",
    de: "Ungefähre Raumgröße",
  },
  ceilingHeight: {
    en: "Ceiling height",
    ru: "Высота потолка",
    es: "Altura del techo",
    fr: "Hauteur sous plafond",
    zh: "层高",
    ja: "天井高",
    de: "Deckenhöhe",
  },
  seatCount: {
    en: "Seats / rows expectation",
    ru: "Ожидаемое число мест / рядов",
    es: "Asientos / filas previstos",
    fr: "Nombre de sièges / rangs souhaité",
    zh: "座位 / 排数预期",
    ja: "座席数 / 列数の想定",
    de: "Erwartete Sitze / Reihen",
  },
  equipmentRoomAvailability: {
    en: "Equipment-room availability",
    ru: "Доступность технической комнаты",
    es: "Disponibilidad de sala técnica",
    fr: "Disponibilité du local technique",
    zh: "设备间条件",
    ja: "機器室の有無",
    de: "Verfügbarkeit eines Technikraums",
  },
  displayPreference: {
    en: "Display path preference",
    ru: "Предпочтение по экранному решению",
    es: "Preferencia de solución de imagen",
    fr: "Préférence de solution image",
    zh: "显示方案偏好",
    ja: "映像方式の希望",
    de: "Präferenz für die Bildlösung",
  },
  audioAmbition: {
    en: "Audio ambition",
    ru: "Аудио-цель",
    es: "Ambición de audio",
    fr: "Ambition audio",
    zh: "音频目标",
    ja: "音響の目標",
    de: "Audio-Anspruch",
  },
  primaryUseCase: {
    en: "Primary use case",
    ru: "Основной сценарий",
    es: "Uso principal",
    fr: "Usage principal",
    zh: "主要使用场景",
    ja: "主な用途",
    de: "Hauptnutzung",
  },
  primaryUseCases: {
    en: "Primary scenarios",
    ru: "Основные сценарии",
    es: "Escenarios principales",
    fr: "Scénarios principaux",
    zh: "主要场景",
    ja: "主なシナリオ",
    de: "Hauptszenarien",
  },
  projectBrief: {
    en: "Project brief",
    ru: "Краткое описание проекта",
    es: "Resumen del proyecto",
    fr: "Brief du projet",
    zh: "项目简述",
    ja: "プロジェクト概要",
    de: "Projektbriefing",
  },
  privacyRequest: {
    en: "Privacy / NDA request",
    ru: "Приватность / NDA",
    es: "Privacidad / NDA",
    fr: "Confidentialité / NDA",
    zh: "隐私 / 保密协议",
    ja: "プライバシー / NDA",
    de: "Datenschutz / NDA",
  },
  attachments: {
    en: "Reference attachments",
    ru: "Материалы для ориентира",
    es: "Archivos de referencia",
    fr: "Pièces de référence",
    zh: "参考附件",
    ja: "参考資料",
    de: "Referenzanhänge",
  },
  planUploadPlaceholder: {
    en: "Plan upload",
    ru: "Планы помещения",
    es: "Planos",
    fr: "Plans",
    zh: "平面图",
    ja: "図面",
    de: "Pläne",
  },
  photoUploadPlaceholder: {
    en: "Photo upload",
    ru: "Фотографии помещения",
    es: "Fotografías",
    fr: "Photographies",
    zh: "照片",
    ja: "写真",
    de: "Fotos",
  },
  consent: {
    en: "I agree to the privacy review and advisory follow-up.",
    ru: "Я согласен(а) на проверку приватности и дальнейшую консультацию.",
    es: "Acepto la revisión de privacidad y el seguimiento de asesoría.",
    fr: "J’accepte la vérification de confidentialité et le suivi de conseil.",
    zh: "我同意隐私审核以及后续顾问沟通。",
    ja: "プライバシー確認とその後のアドバイザリー連絡に同意します。",
    de: "Ich stimme der Datenschutzprüfung und der weiteren Beratung zu.",
  },
};

const sharedPlaceholderByKey: Partial<Record<string, Record<SiteLocale, string>>> = {
  fullName: {
    en: "Name and surname",
    ru: "Имя и фамилия",
    es: "Nombre y apellido",
    fr: "Prénom et nom",
    zh: "姓名",
    ja: "氏名",
    de: "Vor- und Nachname",
  },
  country: {
    en: "Country / region",
    ru: "Страна / регион",
    es: "País / región",
    fr: "Pays / région",
    zh: "国家 / 地区",
    ja: "国 / 地域",
    de: "Land / Region",
  },
  city: {
    en: "City",
    ru: "Город",
    es: "Ciudad",
    fr: "Ville",
    zh: "城市",
    ja: "都市",
    de: "Stadt",
  },
};

const sharedHelperByKey: Partial<Record<string, Record<SiteLocale, string>>> = {
  consent: {
    en: "Montelar uses this request only to continue the advisory conversation.",
    ru: "Montelar использует эту заявку только для продолжения консультации.",
    es: "Montelar usa esta solicitud solo para continuar la conversación de asesoría.",
    fr: "Montelar utilise cette demande uniquement pour poursuivre l’échange de conseil.",
    zh: "Montelar 仅使用此申请继续顾问沟通。",
    ja: "Montelar はこのリクエストをアドバイザリー対応の継続にのみ使用します。",
    de: "Montelar verwendet diese Anfrage nur zur Fortsetzung der Beratung.",
  },
};

const languageOptionLabels: Record<string, Record<SiteLocale, string>> = {
  en: {
    en: "English",
    ru: "Английский",
    es: "Inglés",
    fr: "Anglais",
    zh: "英语",
    ja: "英語",
    de: "Englisch",
  },
  ru: {
    en: "Russian",
    ru: "Русский",
    es: "Ruso",
    fr: "Russe",
    zh: "俄语",
    ja: "ロシア語",
    de: "Russisch",
  },
  es: {
    en: "Spanish",
    ru: "Испанский",
    es: "Español",
    fr: "Espagnol",
    zh: "西班牙语",
    ja: "スペイン語",
    de: "Spanisch",
  },
  fr: {
    en: "French",
    ru: "Французский",
    es: "Francés",
    fr: "Français",
    zh: "法语",
    ja: "フランス語",
    de: "Französisch",
  },
  zh: {
    en: "Chinese",
    ru: "Китайский",
    es: "Chino",
    fr: "Chinois",
    zh: "中文",
    ja: "中国語",
    de: "Chinesisch",
  },
  ja: {
    en: "Japanese",
    ru: "Японский",
    es: "Japonés",
    fr: "Japonais",
    zh: "日语",
    ja: "日本語",
    de: "Japanisch",
  },
  de: {
    en: "German",
    ru: "Немецкий",
    es: "Alemán",
    fr: "Allemand",
    zh: "德语",
    ja: "ドイツ語",
    de: "Deutsch",
  },
};

const sharedOptionLabelByValue: Partial<Record<string, Record<SiteLocale, string>>> = {
  email: { en: "Email", ru: "Email", es: "Correo electrónico", fr: "E-mail", zh: "邮箱", ja: "メール", de: "E-Mail" },
  phone: { en: "Phone", ru: "Телефон", es: "Teléfono", fr: "Téléphone", zh: "电话", ja: "電話", de: "Telefon" },
  whatsapp: { en: "WhatsApp", ru: "WhatsApp", es: "WhatsApp", fr: "WhatsApp", zh: "WhatsApp", ja: "WhatsApp", de: "WhatsApp" },
  signal: { en: "Signal", ru: "Signal", es: "Signal", fr: "Signal", zh: "Signal", ja: "Signal", de: "Signal" },
  "private-cinema": {
    en: "Private cinema",
    ru: "Частный кинозал",
    es: "Cine privado",
    fr: "Cinéma privé",
    zh: "私人影院",
    ja: "プライベートシネマ",
    de: "Privates Kino",
  },
  "media-room": {
    en: "Media room",
    ru: "Медиа-комната",
    es: "Sala multimedia",
    fr: "Salle média",
    zh: "媒体室",
    ja: "メディアルーム",
    de: "Medienraum",
  },
  "estate-renovation": {
    en: "Estate renovation",
    ru: "Реновация резиденции",
    es: "Renovación de residencia",
    fr: "Rénovation de résidence",
    zh: "宅邸翻新",
    ja: "邸宅改修",
    de: "Residenzrenovierung",
  },
  "new-build": {
    en: "New build",
    ru: "Новый проект",
    es: "Obra nueva",
    fr: "Construction neuve",
    zh: "新建项目",
    ja: "新築",
    de: "Neubau",
  },
  retrofit: {
    en: "Retrofit",
    ru: "Модернизация",
    es: "Adaptación",
    fr: "Rénovation technique",
    zh: "改造项目",
    ja: "改修",
    de: "Nachrüstung",
  },
  hybrid: {
    en: "Partial renovation",
    ru: "Частичная реновация",
    es: "Renovación parcial",
    fr: "Rénovation partielle",
    zh: "局部翻新",
    ja: "部分改修",
    de: "Teilrenovierung",
  },
  villa: { en: "Villa", ru: "Вилла", es: "Villa", fr: "Villa", zh: "别墅", ja: "ヴィラ", de: "Villa" },
  apartment: {
    en: "Apartment",
    ru: "Апартаменты",
    es: "Apartamento",
    fr: "Appartement",
    zh: "公寓",
    ja: "アパートメント",
    de: "Apartment",
  },
  estate: {
    en: "Estate residence",
    ru: "Резиденция",
    es: "Residencia",
    fr: "Résidence",
    zh: "宅邸",
    ja: "邸宅",
    de: "Residenz",
  },
  "lounge-upgrade": {
    en: "Lounge / media-room upgrade",
    ru: "Обновление гостиной / медиа-комнаты",
    es: "Mejora de lounge / sala multimedia",
    fr: "Amélioration lounge / salle média",
    zh: "休闲区 / 媒体室升级",
    ja: "ラウンジ / メディアルーム改修",
    de: "Lounge- / Medienraum-Upgrade",
  },
  "dedicated-cinema": {
    en: "Dedicated cinema",
    ru: "Выделенный кинозал",
    es: "Cine dedicado",
    fr: "Cinéma dédié",
    zh: "专属影院",
    ja: "専用シネマルーム",
    de: "Dediziertes Kino",
  },
  "lounge-cinema": {
    en: "Lounge cinema",
    ru: "Кинозона в гостиной",
    es: "Cine lounge",
    fr: "Cinéma lounge",
    zh: "休闲影院",
    ja: "ラウンジシネマ",
    de: "Lounge-Kino",
  },
  "collector-screening-room": {
    en: "Collector screening room",
    ru: "Кинозал коллекционера",
    es: "Sala de visionado de colección",
    fr: "Salle de projection de collectionneur",
    zh: "收藏家放映室",
    ja: "コレクター向け試写室",
    de: "Screening Room für Sammler",
  },
  "vip-screening-suite": {
    en: "VIP screening suite",
    ru: "VIP-кинозал",
    es: "Suite de proyección VIP",
    fr: "Suite de projection VIP",
    zh: "VIP 放映套间",
    ja: "VIP試写スイート",
    de: "VIP-Screening-Suite",
  },
  concept: {
    en: "Concept / early brief",
    ru: "Концепция / ранний бриф",
    es: "Concepto / brief inicial",
    fr: "Concept / brief initial",
    zh: "概念 / 初步简报",
    ja: "コンセプト / 初期ブリーフ",
    de: "Konzept / frühes Briefing",
  },
  design: {
    en: "Design development",
    ru: "Разработка дизайна",
    es: "Desarrollo de diseño",
    fr: "Développement design",
    zh: "设计深化",
    ja: "デザイン開発",
    de: "Designentwicklung",
  },
  "technical-coordination": {
    en: "Technical coordination",
    ru: "Техническая координация",
    es: "Coordinación técnica",
    fr: "Coordination technique",
    zh: "技术协调",
    ja: "技術調整",
    de: "Technische Koordination",
  },
  construction: {
    en: "Construction / fit-out",
    ru: "Стройка / fit-out",
    es: "Obra / fit-out",
    fr: "Chantier / aménagement",
    zh: "施工 / 装修",
    ja: "施工 / フィットアウト",
    de: "Bau / Ausbau",
  },
  "existing-room": {
    en: "Existing room upgrade",
    ru: "Обновление существующего помещения",
    es: "Mejora de sala existente",
    fr: "Amélioration d'une pièce existante",
    zh: "现有空间升级",
    ja: "既存ルームのアップグレード",
    de: "Upgrade eines bestehenden Raums",
  },
  "active-design": {
    en: "Active design phase",
    ru: "Активная стадия проектирования",
    es: "Fase activa de diseño",
    fr: "Phase de conception active",
    zh: "设计进行中",
    ja: "設計進行中",
    de: "Aktive Designphase",
  },
  "3-months": {
    en: "Within 3 months",
    ru: "В течение 3 месяцев",
    es: "En 3 meses",
    fr: "Sous 3 mois",
    zh: "3个月内",
    ja: "3か月以内",
    de: "Innerhalb von 3 Monaten",
  },
  "6-12-months": {
    en: "Within 6-12 months",
    ru: "В течение 6-12 месяцев",
    es: "En 6-12 meses",
    fr: "Sous 6-12 mois",
    zh: "6-12个月内",
    ja: "6-12か月以内",
    de: "Innerhalb von 6-12 Monaten",
  },
  "next-year": {
    en: "Next year",
    ru: "В следующем году",
    es: "El próximo año",
    fr: "L'année prochaine",
    zh: "明年",
    ja: "来年",
    de: "Nächstes Jahr",
  },
  research: {
    en: "Research stage",
    ru: "Стадия изучения",
    es: "Fase de investigación",
    fr: "Phase de recherche",
    zh: "研究阶段",
    ja: "検討段階",
    de: "Recherchephase",
  },
  architect: { en: "Architect", ru: "Архитектор", es: "Arquitecto", fr: "Architecte", zh: "建筑师", ja: "建築家", de: "Architekt" },
  "interior-designer": {
    en: "Interior designer",
    ru: "Дизайнер интерьера",
    es: "Interiorista",
    fr: "Architecte d'intérieur",
    zh: "室内设计师",
    ja: "インテリアデザイナー",
    de: "Innenarchitekt",
  },
  integrator: { en: "Integrator", ru: "Интегратор", es: "Integrador", fr: "Intégrateur", zh: "集成商", ja: "インテグレーター", de: "Integrator" },
  "acoustic-consultant": {
    en: "Acoustic consultant",
    ru: "Акустический консультант",
    es: "Consultor acústico",
    fr: "Consultant acoustique",
    zh: "声学顾问",
    ja: "音響コンサルタント",
    de: "Akustikberater",
  },
  "shipyard-operator": {
    en: "Shipyard / hospitality operator",
    ru: "Верфь / hospitality-оператор",
    es: "Astillero / operador hotelero",
    fr: "Chantier naval / opérateur hospitality",
    zh: "船厂 / 酒店运营方",
    ja: "造船所 / ホスピタリティ運営者",
    de: "Werft / Hospitality-Betreiber",
  },
};

const submitLabelByMode: Record<string, Record<SiteLocale, string>> = {
  "private-audition": {
    en: "Request private consultation",
    ru: "Запросить частную консультацию",
    es: "Solicitar consulta privada",
    fr: "Demander une consultation privée",
    zh: "申请专属咨询",
    ja: "個別相談を依頼する",
    de: "Private Beratung anfragen",
  },
  "private-demo": {
    en: "Request private demonstration",
    ru: "Запросить частную демонстрацию",
    es: "Solicitar demostración privada",
    fr: "Demander une démonstration privée",
    zh: "申请专属演示",
    ja: "個別デモを依頼する",
    de: "Private Demonstration anfragen",
  },
  "product-inquiry": {
    en: "Request consultation",
    ru: "Запросить консультацию",
    es: "Solicitar consulta",
    fr: "Demander une consultation",
    zh: "申请咨询",
    ja: "相談を依頼する",
    de: "Beratung anfragen",
  },
  "project-consultation": {
    en: "Request project consultation",
    ru: "Запросить консультацию по проекту",
    es: "Solicitar consulta de proyecto",
    fr: "Demander une consultation de projet",
    zh: "申请项目咨询",
    ja: "プロジェクト相談を依頼する",
    de: "Projektberatung anfragen",
  },
  "senior-project-consultation": {
    en: "Request senior consultation",
    ru: "Запросить старшую консультацию",
    es: "Solicitar consulta senior",
    fr: "Demander une consultation senior",
    zh: "申请高级顾问咨询",
    ja: "上位コンサルテーションを依頼する",
    de: "Senior-Beratung anfragen",
  },
  "technical-qualification": {
    en: "Request technical review",
    ru: "Запросить техническую консультацию",
    es: "Solicitar revisión técnica",
    fr: "Demander une revue technique",
    zh: "申请技术评估",
    ja: "技術レビューを依頼する",
    de: "Technische Prüfung anfragen",
  },
};

export function getInquiryUiCopy(locale: SiteLocale): InquiryUiCopy {
  return inquiryUiCopyByLocale[locale];
}

export function localizeSharedInquiryField(
  field: CmsProductInquiryField,
  locale: SiteLocale,
): CmsProductInquiryField {
  const uiCopy = getInquiryUiCopy(locale);
  const label = sharedFieldLabelByKey[field.fieldKey]?.[locale] ?? field.label;
  const placeholder = sharedPlaceholderByKey[field.fieldKey]?.[locale] ?? field.placeholder;
  const helperText =
    field.fieldType === "file-placeholder"
      ? uiCopy.filePlaceholderNote
      : sharedHelperByKey[field.fieldKey]?.[locale] ?? field.helperText;
  const options = field.options?.map((option) => ({
    ...option,
    label:
      field.fieldKey === "preferredLanguage"
        ? languageOptionLabels[option.value]?.[locale] ?? option.label
        : sharedOptionLabelByValue[option.value]?.[locale] ?? option.label,
  }));

  return {
    ...field,
    label,
    ...(placeholder ? { placeholder } : {}),
    ...(helperText ? { helperText } : {}),
    ...(options?.length ? { options } : {}),
  };
}

export function localizeInquiryFormRuntimeCopy(
  form: CmsProductInquiryForm,
  locale: SiteLocale,
): CmsProductInquiryForm {
  const uiCopy = getInquiryUiCopy(locale);
  const localizedFields = form.fields.map((field) => localizeSharedInquiryField(field, locale));
  const localizedConsentField = localizedFields.find((field) => field.fieldType === "consent");

  return {
    ...form,
    submitLabel: submitLabelByMode[form.formMode]?.[locale] ?? form.submitLabel,
    successTitle: locale === "en" ? form.successTitle : uiCopy.successTitle,
    successMessage:
      locale === "en"
        ? form.successMessage
        : uiCopy.successMessage,
    consentText: localizedConsentField?.label ?? form.consentText,
    fields: localizedFields,
  };
}
